#ifndef _PRIVMXLIB_UTILS_DEBUG_CONFIG_HPP_
#define _PRIVMXLIB_UTILS_DEBUG_CONFIG_HPP_


/* #undef PRIVMX_USE_DEBUG */
/* #undef PRIVMX_DEBUG_USE_CERR */
/* #undef PRIVMX_DEBUG_OUTPUT_TIMESTAMP_ON_START */
/* #undef PRIVMX_DEBUG_OUTPUT_TIMESTAMP_ON_CHECKPOINT */
/* #undef PRIVMX_DEBUG_OUTPUT_TIMESTAMP_ON_STOP */

/* #undef PRIVMX_DEBUG_TIME */


#endif // _PRIVMXLIB_UTILS_DEBUG_CONFIG_HPP_

